dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
  - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
  - gpg -a --export E084DAB9 | sudo apt-key add -
install:
  - sudo apt-get -y update
  - sudo apt-get install -y libgdal-dev gdal-bin r-base
  - pip install -r requirements.txt
  - pip install codecov
  - pip install coverage
script: coverage run run_tests.py
services:
  -postgresql
addons:
  postgresql: "9.6"
sudo: false
before_script:
  - sudo apt-get install postgis -y -q
  - psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'postgres';"
  - psql -U postgres -c "CREATE EXTENSION postgis;"
  - sh tests/download_test_data.sh
  - mkdir /home/travis/niamoto
  - cp -r tests/test_data/test_niamoto_home/* /home/travis/niamoto

after_success:
  - codecov
