dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - sudo apt-get -y update
  - sudo apt-get install -y libgdal-dev gdal-bin
  - pip install -r requirements.txt
  - pip install codecov
  - pip install coverage
script: coverage run run_tests.py
services:
  -postgresql
before_script:
  - psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'postgres';"
  - psql -U postgres -c "CREATE EXTENSION postgis;"
  - sh tests/download_test_data.sh
addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3
after_success:
  - codecov
