dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install --user codecov"
script: python run_tests.py
services:
  -postgresql
before_script:
  - psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'postgres';"
  - psql -U postgres -c "CREATE EXTENSION postgis;"
addons:
  postgresql: "9.5"
after_success:
  - codecov
