dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "python setup.py -q install -e"
script: python tests/run_tests.py
services:
  -postgresql
before_script:
  - psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'postgres';"
  - psql -U postgres -c "CREATE EXTENSION postgis;"
addons:
  postgresql: "9.5"
