dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install coverage
script: coverage run run_tests.py
services:
  -postgresql
before_script:
  - psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'postgres';"
  - psql -U postgres -c "CREATE EXTENSION postgis;"
  - sh tests/download_test_data.sh
  - add-apt-repository ppa:ubuntugis/ppa
  - apt-get update
  - apt-get install python-numpy gdal-bin libgdal-dev
addons:
  postgresql: "9.5"
after_success:
  - codecov
