dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
  - sudo add-apt-repository 'deb [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu xenial/'
  - sudo apt-get -y update
  - sudo apt-get install r-base
install:
  - sudo apt-get -y update
  - sudo apt-get install -y libgdal-dev gdal-bin postgis
  - pip install -r requirements.txt
  - pip install codecov
  - pip install coverage
script: coverage run run_tests.py
services:
  -postgresql
before_script:
  - psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'postgres';"
  - psql -U postgres -c "CREATE EXTENSION postgis;"
  - sh tests/download_test_data.sh

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3
after_success:
  - codecov
